---
abstract: 'manipulate blocks of code to assemble them into subs'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.96
  Test::Warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Sub::Block
name: Sub-Block
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Exporter::TypeTiny: 0.012
  Moo: 1.000000
  PadWalker: 0
  Sub::Quote: 0
  namespace::clean: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Sub-Block
  homepage: https://metacpan.org/release/Sub-Block
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-sub-block
version: 0.001
